a = input('Qual seu nome?')
a = a + (',')
print(a)
b = input('Sua idade?')
print(a)
c = input('O que voce gosta?')
print(a)
d = input('Sabe o que detecto em você?')
print(a,'você deve ser a melhor pessoa do mundo')
